services:
  mongodb-btg:
    image: mongo
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=123
    networks:
      - mongo-compose-btg-network

  mongo-express-btg:
    image: mongo-express
    container_name: mexpress-btg
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=123
      - ME_CONFIG_MONGODB_URL=mongodb://admin:123@mongodb-btg:27017/?authSource=admin
      - ME_CONFIG_BASICAUTH_USERNAME=mexpress
      - ME_CONFIG_BASICAUTH_PASSWORD=mexpress
    links:
      - mongodb-btg
    networks:
      - mongo-compose-btg-network
    restart: unless-stopped
    ports:
      - "8091:8081"

  rabbitmq-btg:
    image: rabbitmq:3.13-management
    ports:
      - 15672:15672
      - 5672:5672
networks:
  mongo-compose-btg-network:
    driver: bridge